EverCareCommunity/Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EverCareCommunity.Data;
using EverCareCommunity.Models;
using Microsoft.AspNetCore.Authorization;

namespace EverCareCommunity.Controllers
{
    // needs login 
    [Authorize(Roles = "Admin, Manager")]
    public class AddressesController : Controller
    {
        private readonly EverCareCommunityContext _context;

        public AddressesController(EverCareCommunityContext context)
        {
            _context = context;
        }

        // GET: Addresses
        public async Task<IActionResult> Index(
      string sortOrder, 
      string currentFilter,
      string searchString,
      int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            



            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            var addresses = _context.Addresses
           .Include(a => a.ElderlyResident) // Ensure related ElderlyResident is included
    .AsNoTracking();


            if (!String.IsNullOrEmpty(searchString))
            {
                addresses = addresses.Where(s => s.Street.Contains(searchString) || s.Street.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    addresses = addresses.OrderByDescending(s => s.City);
                    break;
                case "Date":
                    addresses = addresses.OrderBy(s => s.City);
                    break;
            }

            int pageSize = 3;
            return View(await PaginatedList<Address>.CreateAsync(addresses.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Addresses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Addresses == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .Include(a => a.ElderlyResident)
                .FirstOrDefaultAsync(m => m.AddressID == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // GET: Addresses/Create
        public IActionResult Create()
        {
            ViewData["ResidentID"] = new SelectList(_context.ElderlyResidents, "ResidentID", "FirstName");
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AddressID,ResidentID,Street,City,ZipCode,Relationship,PhoneNumber")] Address address)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(address);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ResidentID"] = new SelectList(_context.ElderlyResidents, "ResidentID", "FirstName", address.ResidentID);
            return View(address);
        }

        // GET: Addresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Addresses == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses.FindAsync(id);
            if (address == null)
            {
                return NotFound();
            }
            ViewData["ResidentID"] = new SelectList(_context.ElderlyResidents, "ResidentID", "FirstName", address.ResidentID);
            return View(address);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AddressID,ResidentID,Street,City,ZipCode,Relationship,PhoneNumber")] Address address)
        {
            if (id != address.AddressID)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.AddressID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ResidentID"] = new SelectList(_context.ElderlyResidents, "ResidentID", "FirstName", address.ResidentID);
            return View(address);
        }

        // GET: Addresses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Addresses == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .Include(a => a.ElderlyResident)
                .FirstOrDefaultAsync(m => m.AddressID == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Addresses == null)
            {
                return Problem("Entity set 'EverCareCommunityContext.Addresses'  is null.");
            }
            var address = await _context.Addresses.FindAsync(id);
            if (address != null)
            {
                _context.Addresses.Remove(address);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AddressExists(int id)
        {
          return (_context.Addresses?.Any(e => e.AddressID == id)).GetValueOrDefault();
        }
    }
}

EverCareCommunity/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EverCareCommunity.Data;
using EverCareCommunity.Models;
using Microsoft.AspNetCore.Authorization;

namespace EverCareCommunity.Controllers
{
    [Authorize(Roles = "Manager, Admin")]
    public class DoctorsController : Controller
    {
        private readonly EverCareCommunityContext _context;

        public DoctorsController(EverCareCommunityContext context)
        {
            _context = context;
        }

        // GET: Doctors
        public async Task<IActionResult> Index(
     string sortOrder,
     string currentFilter,
     string searchString,
     int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";



            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var doctors = _context.Doctors
                .Select(s => new Doctor
                {
                    DoctorID = s.DoctorID,
                    FirstName = s.FirstName,
                    LastName = s.LastName,
                    Email = s.Email,
                    PhoneNumber = s.PhoneNumber,
                    LicenseNumber = s.LicenseNumber,
                    Availability = s.Availability,
                });

            if (!String.IsNullOrEmpty(searchString))
            {
                doctors = doctors.Where(s => s.FirstName.Contains(searchString) || s.LastName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    doctors = doctors.OrderByDescending(s => s.FirstName);
                    break;
                case "Date":
                    doctors = doctors.OrderBy(s => s.FirstName);
                    break;
            }

            int pageSize = 5;
            return View(await PaginatedList<Doctor>.CreateAsync(doctors.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
            // GET: Doctors/Details/5
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
                .FirstOrDefaultAsync(m => m.DoctorID == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DoctorID,FirstName,LastName,Email,LicenseNumber,PhoneNumber,Availability")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(doctor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors.FindAsync(id);
            if (doctor == null)
            {
                return NotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DoctorID,FirstName,LastName,Email,LicenseNumber,PhoneNumber,Availability")] Doctor doctor)
        {
            if (id != doctor.DoctorID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doctor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(doctor.DoctorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
                .FirstOrDefaultAsync(m => m.DoctorID == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Doctors == null)
            {
                return Problem("Entity set 'EverCareCommunityContext.Doctors'  is null.");
            }
            var doctor = await _context.Doctors.FindAsync(id);
            if (doctor != null)
            {
                _context.Doctors.Remove(doctor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoctorExists(int id)
        {
          return (_context.Doctors?.Any(e => e.DoctorID == id)).GetValueOrDefault();
        }
    }
}

EverCareCommunity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EverCareCommunity</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EverCareCommunity.styles.css" asp-append-version="true" />
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

</head>
<body>
    <div class="d-flex">
        <!-- Sidebar -->
        <aside class="sidebar">
            <h2 class="sidebar-title">EverCareCommunity</h2>
            <ul class="sidebar-nav">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="ElderlyResidents" asp-action="Index">Resident</a></li>
                <li><a asp-controller="Doctors" asp-action="Index">Doctor</a></li>
                <li><a asp-controller="Caregivers" asp-action="Index">Caregiver</a></li>
                <li><a asp-controller="Addresses" asp-action="Index">Address</a></li>
                <li><a asp-controller="Appointments" asp-action="Index">Appointment</a></li>
                <li><a asp-controller="EmergencyContacts" asp-action="Index">Contacts</a></li>
                <li><a asp-controller="MedicalConditions" asp-action="Index">Medical Condition</a></li>
                <li><a asp-controller="MedicalRecords" asp-action="Index">Medical Record</a></li>
                <li><a asp-controller="Home" asp-action="Privacy">Privacy</a></li>
            </ul>
            <div class="login-partial">
                <partial name="_LoginPartial.cshtml" />
            </div>
        </aside>

        <!-- Main Content -->
        <div class="main-content">
            <!-- Hero Section -->
            <section class="hero text-center mb-5">
                <h1>Welcome to EverCare Community</h1>
                <div class="btn-group mt-3">
                    <a asp-controller="ElderlyResidents" asp-action="Create" class="btn btn-warning text-dark">Join as a Resident</a>
                    <a asp-controller="Caregivers" asp-action="Create" class="btn btn-light">Apply as a Caregiver</a>
                    <a asp-controller="Doctors" asp-action="Create" class="btn btn-info text-white">Register as a Doctor</a>
                </div>
            </section>

            <!-- Page Body -->
            <main role="main" class="container pb-3">
                @RenderBody()
            </main>

            <!-- Footer -->
            <footer class="text-center mt-5">
                <hr />
                <p>&copy; 2025 - EverCareCommunity | <a asp-controller="Home" asp-action="Privacy">Privacy Policy</a></p>
            </footer>
        </div>
    </div>

    <!-- Password Strength Script -->
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const passwordInput = document.querySelector("#Input_Password");
            const strengthBar = document.querySelector("#password-strength");

            passwordInput.addEventListener("input", function () {
                const val = passwordInput.value;
                let strength = 0;
                if (val.length > 7) strength++;
                if (/[A-Z]/.test(val)) strength++;
                if (/[a-z]/.test(val)) strength++;
                if (/[0-9]/.test(val)) strength++;
                if (/[\W]/.test(val)) strength++;

                strengthBar.className = "progress-bar";
                strengthBar.style.width = (strength * 20) + "%";
                strengthBar.classList.add(strength >= 4 ? "bg-success" : strength >= 3 ? "bg-warning" : "bg-danger");
            });
        });
    </script>


    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>